# Generated by Django 5.2.7 on 2025-10-21 00:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='mensaje',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='asunto',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='fecha_push',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificacion',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='plataforma',
            field=models.CharField(choices=[('web', 'Web'), ('email', 'Email'), ('push', 'Push'), ('sms', 'SMS')], default='web', max_length=20),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('success', 'Éxito'), ('promocion', 'Promoción'), ('sistema', 'Sistema')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuarios',
            field=models.ManyToManyField(blank=True, help_text='Usuarios que deberían ver esta notificación', related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NotificacionLeida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lectura', models.DateTimeField(auto_now_add=True)),
                ('plataforma_lectura', models.CharField(default='web', max_length=20)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='usuarios.notificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación Leída',
                'verbose_name_plural': 'Notificaciones Leídas',
                'db_table': 'notificacion_leida',
                'ordering': ['-fecha_lectura'],
                'unique_together': {('usuario', 'notificacion')},
            },
        ),
    ]
