# Generated by Django 5.2.7 on 2025-11-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_notificacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Token de Firebase Cloud Messaging para notificaciones push', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fcm_token_actualizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
