# Generated by Django 5.2.7 on 2025-10-22 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la categoría', null=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del producto', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada del producto')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del producto', max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad en inventario')),
                ('url_imagen_principal', models.URLField(blank=True, help_text='URL de la imagen principal del producto', max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(help_text='Categoría a la que pertenece el producto', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL de la imagen', max_length=500)),
                ('descripcion', models.CharField(blank=True, help_text='Texto alternativo o descripción de la imagen', max_length=200, null=True)),
                ('producto', models.ForeignKey(help_text='Producto al que pertenece la imagen', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
            },
        ),
    ]
