# Generated by Django 5.2.7 on 2025-10-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.FloatField(default=0.0, help_text='Descuento aplicado al producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='Generico', help_text='Marca del producto', max_length=50),
        ),
    ]
