# Generated by Django 5.2.7 on 2025-10-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_descuento_producto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenproducto',
            name='public_id',
            field=models.CharField(blank=True, help_text='Public ID de Cloudinary para poder eliminar la imagen', max_length=255, null=True),
        ),
    ]
