# Generated by Django 5.2.7 on 2025-11-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_imagenproducto_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(default=True, help_text='Indica si el producto está activo o inactivo'),
        ),
    ]
