# Generated by Django 5.2.7 on 2025-11-10 00:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0004_producto_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrecimientoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del análisis')),
                ('periodo', models.CharField(help_text='Período analizado (YYYY-MM)', max_length=10, verbose_name='Período')),
                ('ventas_mes_actual', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ventas mes actual')),
                ('ventas_mes_anterior', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ventas mes anterior')),
                ('tendencia', models.CharField(choices=[('CRECIMIENTO_FUERTE', 'Crecimiento Fuerte'), ('CRECIMIENTO', 'Crecimiento'), ('ESTABLE', 'Estable'), ('DECRECIMIENTO', 'Decrecimiento'), ('DECRECIMIENTO_FUERTE', 'Decrecimiento Fuerte')], max_length=25, verbose_name='Tendencia')),
                ('porcentaje_cambio', models.FloatField(default=0, help_text='Ej: +15.5 = creció 15.5%', verbose_name='Porcentaje de cambio')),
                ('estimacion_proximo_mes', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estimación próximo mes')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crecimientos', to='productos.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Crecimiento de Categoría',
                'verbose_name_plural': 'Crecimiento de Categorías',
                'ordering': ['-fecha_analisis', '-porcentaje_cambio'],
                'unique_together': {('categoria', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='PrediccionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('periodo', models.CharField(help_text='Formato: 2025-12', max_length=10, verbose_name='Período')),
                ('anio', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)], verbose_name='Año')),
                ('mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes')),
                ('monto_estimado', models.DecimalField(decimal_places=2, help_text='Cuánto dinero se espera vender', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ventas estimadas')),
                ('cantidad_estimada', models.IntegerField(default=0, help_text='Cuántos productos se venderán', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Productos estimados')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('categoria', models.ForeignKey(blank=True, help_text='Si es null = predicción total', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='productos.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Predicción de Venta',
                'verbose_name_plural': 'Predicciones de Ventas',
                'ordering': ['-anio', '-mes', 'categoria'],
                'indexes': [models.Index(fields=['anio', 'mes'], name='prediccione_anio_698ce0_idx'), models.Index(fields=['categoria'], name='prediccione_categor_26908a_idx'), models.Index(fields=['activo'], name='prediccione_activo_49ecfe_idx')],
                'unique_together': {('periodo', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='ProductoMasVendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Formato YYYY-MM', max_length=10, verbose_name='Período')),
                ('cantidad_vendida', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unidades vendidas')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total vendido')),
                ('ranking', models.IntegerField(help_text='1 = más vendido', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Posición en el ranking')),
                ('estimacion_siguiente_mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estimación próximo mes (unidades)')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Producto Más Vendido',
                'verbose_name_plural': 'Productos Más Vendidos',
                'ordering': ['periodo', 'ranking'],
                'unique_together': {('producto', 'periodo')},
            },
        ),
    ]
